#!/usr/bin/env bash
#HI#

for (( a=1 ; a<=100 ; a++ ; )) ;
do
	if [[ $(( a % 3 )) == 0 ]] ; 
	then
		if [[ $(( a % 5 )) == ]] ; 
		then
			echo "FizzBuzz"
		else 
			echo "Fizz"
		fi
	else 
		if [[ $(( a % 5 )) == 0]] ; 
		then
			echo "Buzz"
		else 
			echo "$a"
		fi
	fi
don
