#!/usr/bin/env bash
#HI#

while IFS=":" read -r USERNAME PASSWORD U_ID G_ID GECOS H_DIR C_SHELL
do
	echo "The user $USERNAME is part of the $G_ID gang, lives in $H_DIR and rides $C_SHELL. $U_ID's place is protected by the passcode $PASSWORD, more info about the user here: $GECOS"
done < /etc/passwd
