#!/usr/bin/env bash
#This sript dsplays numbers from 1 to 20#

h=$(( 0 ))
while [ $h -le 12 ] ;
do
       echo "hour: ${h}"

       m=1
       while [ $m -le 59 ] ;
       do
	       echo $m
	       m=$(( m + 1 ))
       done 
       h=$(( h + 1 ))
done
