#!/usr/bin/env bash
#This sript dsplays numbers from 1 to 20#

a=$((0))
while [ $a -le 12 ] ;
do
       echo "Hour: ${a}"
       b=1
       while [ $b -le 59 ] ;
       do
	       echo $b
	       b=$((b + 1))
       done 
       a=$((a + 1))
done
