#!/usr/bin/env bash
#This sript dsplays numbers from 1 to 20#

a=1
while [ $a -le 12 ] ;
do
       echo "hour ${a}"

       b=1
       while [ $b -le 59 ] ;
       do
	       echo "minute ${b}"
	       b=$(( b + 1 ))
       done 
       a=$(( a + 1 ))
done
