#!/usr/bin/env bash
#HI#
filename=school
if [[ -f $filename ]] ; 
then
echo "${filename} file exists"

if [[ -s $filename ]] ;
then
	echo "${filename} file is not empty"
else 
	echo "${filename} file is empty"
fi
echo "${filename} is a regular file"

else 
	if  [[ -d $filename ]] ; 
	then
		echo "${filename} file exists"
		if [ "$(ls -A $filename)" ] ;
		then
		echo "${filename} file is empty"
	else 	
		echo "${filename} file is not empty"
		fi
	else
		echo "${filename} file does not exist"
	fi
fi
