#!/usr/bin/env bash
#HI#

if [[ -f $school ]] ; 
then
echo "${school} file exists"

if [[ -s $school ]] ;
then
	echo "${school} file is not empty"
else 
	echo "${school} file is empty"
fi
echo "${school} is a regular file"

else 
	if  [[ -d $school ]] ; 
	then
		echo "${school} file exists"
		if [ "$(ls -A $school)" ] ;
		then
		echo "${school} file is empty"
	else 	
		echo "${school} file is not empty"
		fi
	else
		echo "${school} file does not exist"
	fi
fi
