#!/usr/bin/env bash
#task 10
start () {
./manage_my_process & proc=$( pgrep -fn manage_my_process )
echo "$proc" > /var/run/my_process.pid
echo "manage_my_process started"
}
stop() { 
pid=$( cat /var/run/myprocess.pid )
kill -9 "$pid"
rm /var/run/my_process.pid
echo "manage_my_process stopped"
}
restart() {
#proc=$(pidof ./manage_my_process)
kill -9 "$pid"
rm /var/run/my_process.pid
./manage_my_process & proc=$( pgrep -fn manage_my_process )
echo "$proc" > /var/run/my_process.pid
echo "manage_my_process restarted"
}
case "$1" in 
start)
start
;;
stop)
stop
;;
restart)
restart
;;
*)
	echo "Usage: manage_my_process {start|stop|restart}"
esac
